In [1]:
from bs4 import BeautifulSoup

In [17]:
import requests
import pandas as pd
import numpy as np

In [32]:
soup = pd.read_html("table_9.html")
soup1 = pd.read_html('table_62.html')
soup2 = pd.read_html('table_12.html')

In [33]:
soup

[                                         0   \
 0                                       NaN
 1                                         Â
 2                                         Â
 3                 Revenues ($ millions) (2)
 4                   Petroleum and chemicals
 5                       Metals and minerals
 6                           Forest products
 7                                      Coal
 8                     Grain and fertilizers
 9                                Intermodal
 10                               Automotive
 11                   Total freight revenues
 12                           Other revenues
 13                           Total revenues
 14  Revenue ton miles (RTMs) (millions) (3)
 15                  Petroleum and chemicals
 16                      Metals and minerals
 17                          Forest products
 18                                     Coal
 19                    Grain and fertilizers
 20                               Intermodal
 21                               Automotive
 22                               Total RTMs
 23    Freight revenue / RTM (cents) (2) (3)
 24                  Petroleum and chemicals
 25                      Metals and minerals
 26                          Forest products
 27                                     Coal
 28                    Grain and fertilizers
 29                               Intermodal
 30                               Automotive
 31              Total freight revenue / RTM
 32                 Carloads (thousands) (3)
 33                  Petroleum and chemicals
 34                      Metals and minerals
 35                          Forest products
 36                                     Coal
 37                    Grain and fertilizers
 38                               Intermodal
 39                               Automotive
 40                           Total carloads
 41    Freight revenue / carload ($) (2) (3)
 42                  Petroleum and chemicals
 43                      Metals and minerals
 44                          Forest products
 45                                     Coal
 46                    Grain and fertilizers
 47                               Intermodal
 48                               Automotive
 49          Total freight revenue / carload

                                          1   \
 0                                       NaN
 1                                         Â
 2                                         Â
 3                 Revenues ($ millions) (2)
 4                   Petroleum and chemicals
 5                       Metals and minerals
 6                           Forest products
 7                                      Coal
 8                     Grain and fertilizers
 9                                Intermodal
 10                               Automotive
 11                   Total freight revenues
 12                           Other revenues
 13                           Total revenues
 14  Revenue ton miles (RTMs) (millions) (3)
 15                  Petroleum and chemicals
 16                      Metals and minerals
 17                          Forest products
 18                                     Coal
 19                    Grain and fertilizers
 20                               Intermodal
 21                               Automotive
 22                               Total RTMs
 23    Freight revenue / RTM (cents) (2) (3)
 24                  Petroleum and chemicals
 25                      Metals and minerals
 26                          Forest products
 27                                     Coal
 28                    Grain and fertilizers
 29                               Intermodal
 30                               Automotive
 31              Total freight revenue / RTM
 32                 Carloads (thousands) (3)
 33                  Petroleum and chemicals
 34                      Metals and minerals
 35                          Forest products
 36                                     Coal
 37                    Grain and fertilizers
 38                               Intermodal
 39                               Automotive
 40                           Total carloads
 41    Freight revenue / carload ($) (2) (3)
 42                  Petroleum and chemicals
 43                      Metals and minerals
 44                          Forest products
 45                                     Coal
 46                    Grain and fertilizers
 47                               Intermodal
 48                               Automotive
 49          Total freight revenue / carload

                                          2                            3   \
 0                                       NaN                          NaN
 1                                         Â  Three months ended March 31
 2                                         Â                         2022
 3                 Revenues ($ millions) (2)                          NaN
 4                   Petroleum and chemicals                         756Â
 5                       Metals and minerals                         406Â
 6                           Forest products                         426Â
 7                                      Coal                         195Â
 8                     Grain and fertilizers                         604Â
 9                                Intermodal                       1,056Â
 10                               Automotive                         165Â
 11                   Total freight revenues                       3,608Â
 12                           Other revenues                         100Â
 13                           Total revenues                       3,708Â
 14  Revenue ton miles (RTMs) (millions) (3)                          NaN
 15                  Petroleum and chemicals                      11,559Â
 16                      Metals and minerals                       6,263Â
 17                          Forest products                       5,819Â
 18                                     Coal                       5,368Â
 19                    Grain and fertilizers                      13,351Â
 20                               Intermodal                      13,556Â
 21                               Automotive                         638Â
 22                               Total RTMs                      56,554Â
 23    Freight revenue / RTM (cents) (2) (3)                          NaN
 24                  Petroleum and chemicals                        6.54Â
 25                      Metals and minerals                        6.48Â
 26                          Forest products                        7.32Â
 27                                     Coal                        3.63Â
 28                    Grain and fertilizers                        4.52Â
 29                               Intermodal                        7.79Â
 30                               Automotive                       25.86Â
 31              Total freight revenue / RTM                        6.38Â
 32                 Carloads (thousands) (3)                          NaN
 33                  Petroleum and chemicals                         159Â
 34                      Metals and minerals                         209Â
 35                          Forest products                          78Â
 36                                     Coal                         118Â
 37                    Grain and fertilizers                         145Â
 38                               Intermodal                         589Â
 39                               Automotive                          48Â
 40                           Total carloads                       1,346Â
 41    Freight revenue / carload ($) (2) (3)                          NaN
 42                  Petroleum and chemicals                       4,755Â
 43                      Metals and minerals                       1,943Â
 44                          Forest products                       5,462Â
 45                                     Coal                       1,653Â
 46                    Grain and fertilizers                       4,166Â
 47                               Intermodal                       1,793Â
 48                               Automotive                       3,438Â
 49          Total freight revenue / carload                       2,681Â

                              4                            5   \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                          2022                         2022
 3                           NaN                          NaN
 4                          756Â                          NaN
 5                          406Â                          NaN
 6                          426Â                          NaN
 7                          195Â                          NaN
 8                          604Â                          NaN
 9                        1,056Â                          NaN
 10                         165Â                          NaN
 11                       3,608Â                          NaN
 12                         100Â                          NaN
 13                       3,708Â                          NaN
 14                          NaN                          NaN
 15                      11,559Â                          NaN
 16                       6,263Â                          NaN
 17                       5,819Â                          NaN
 18                       5,368Â                          NaN
 19                      13,351Â                          NaN
 20                      13,556Â                          NaN
 21                         638Â                          NaN
 22                      56,554Â                          NaN
 23                          NaN                          NaN
 24                        6.54Â                          NaN
 25                        6.48Â                          NaN
 26                        7.32Â                          NaN
 27                        3.63Â                          NaN
 28                        4.52Â                          NaN
 29                        7.79Â                          NaN
 30                       25.86Â                          NaN
 31                        6.38Â                          NaN
 32                          NaN                          NaN
 33                         159Â                          NaN
 34                         209Â                          NaN
 35                          78Â                          NaN
 36                         118Â                          NaN
 37                         145Â                          NaN
 38                         589Â                          NaN
 39                          48Â                          NaN
 40                       1,346Â                          NaN
 41                          NaN                          NaN
 42                       4,755Â                          NaN
 43                       1,943Â                          NaN
 44                       5,462Â                          NaN
 45                       1,653Â                          NaN
 46                       4,166Â                          NaN
 47                       1,793Â                          NaN
 48                       3,438Â                          NaN
 49                       2,681Â                          NaN

                              6                            7   \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                          2021                         2021
 3                           NaN                          NaN
 4                          661Â                         661Â
 5                          368Â                         368Â
 6                          429Â                         429Â
 7                          126Â                         126Â
 8                          713Â                         713Â
 9                          968Â                         968Â
 10                         158Â                         158Â
 11                       3,423Â                       3,423Â
 12                         112Â                         112Â
 13                       3,535Â                       3,535Â
 14                          NaN                          NaN
 15                      10,732Â                      10,732Â
 16                       6,293Â                       6,293Â
 17                       6,670Â                       6,670Â
 18                       4,026Â                       4,026Â
 19                      17,841Â                      17,841Â
 20                      15,233Â                      15,233Â
 21                         659Â                         659Â
 22                      61,454Â                      61,454Â
 23                          NaN                          NaN
 24                        6.16Â                        6.16Â
 25                        5.85Â                        5.85Â
 26                        6.43Â                        6.43Â
 27                        3.13Â                        3.13Â
 28                        4.00Â                        4.00Â
 29                        6.35Â                        6.35Â
 30                       23.98Â                       23.98Â
 31                        5.57Â                        5.57Â
 32                          NaN                          NaN
 33                         150Â                         150Â
 34                         223Â                         223Â
 35                          86Â                          86Â
 36                          69Â                          69Â
 37                         176Â                         176Â
 38                         676Â                         676Â
 39                          51Â                          51Â
 40                       1,431Â                       1,431Â
 41                          NaN                          NaN
 42                       4,407Â                       4,407Â
 43                       1,650Â                       1,650Â
 44                       4,988Â                       4,988Â
 45                       1,826Â                       1,826Â
 46                       4,051Â                       4,051Â
 47                       1,432Â                       1,432Â
 48                       3,098Â                       3,098Â
 49                       2,392Â                       2,392Â

                              8                            9   \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                          2021         % Change Fav (Unfav)
 3                           NaN                          NaN
 4                           NaN                          14Â
 5                           NaN                          10Â
 6                           NaN                          (1Â
 7                           NaN                          55Â
 8                           NaN                         (15Â
 9                           NaN                           9Â
 10                          NaN                           4Â
 11                          NaN                           5Â
 12                          NaN                         (11Â
 13                          NaN                           5Â
 14                          NaN                          NaN
 15                          NaN                           8Â
 16                          NaN                         âÂ
 17                          NaN                         (13Â
 18                          NaN                          33Â
 19                          NaN                         (25Â
 20                          NaN                         (11Â
 21                          NaN                          (3Â
 22                          NaN                          (8Â
 23                          NaN                          NaN
 24                          NaN                           6Â
 25                          NaN                          11Â
 26                          NaN                          14Â
 27                          NaN                          16Â
 28                          NaN                          13Â
 29                          NaN                          23Â
 30                          NaN                           8Â
 31                          NaN                          15Â
 32                          NaN                          NaN
 33                          NaN                           6Â
 34                          NaN                          (6Â
 35                          NaN                          (9Â
 36                          NaN                          71Â
 37                          NaN                         (18Â
 38                          NaN                         (13Â
 39                          NaN                          (6Â
 40                          NaN                          (6Â
 41                          NaN                          NaN
 42                          NaN                           8Â
 43                          NaN                          18Â
 44                          NaN                          10Â
 45                          NaN                          (9Â
 46                          NaN                           3Â
 47                          NaN                          25Â
 48                          NaN                          11Â
 49                          NaN                          12Â

                              10                           11  \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2          % Change Fav (Unfav)         % Change Fav (Unfav)
 3                           NaN                          NaN
 4                           14Â                            %
 5                           10Â                            %
 6                           (1Â                           %)
 7                           55Â                            %
 8                          (15Â                           %)
 9                            9Â                            %
 10                           4Â                            %
 11                           5Â                            %
 12                         (11Â                           %)
 13                           5Â                            %
 14                          NaN                          NaN
 15                           8Â                            %
 16                         âÂ                            %
 17                         (13Â                           %)
 18                          33Â                            %
 19                         (25Â                           %)
 20                         (11Â                           %)
 21                          (3Â                           %)
 22                          (8Â                           %)
 23                          NaN                          NaN
 24                           6Â                            %
 25                          11Â                            %
 26                          14Â                            %
 27                          16Â                            %
 28                          13Â                            %
 29                          23Â                            %
 30                           8Â                            %
 31                          15Â                            %
 32                          NaN                          NaN

In [34]:
soup1

[                                0                                1   \
 0                              NaN                              NaN
 1                              NaN                              NaN
 2                      In millions                      In millions
 3             Debt obligations (1)             Debt obligations (1)
 4     Interest on debt obligations     Interest on debt obligations
 5        Finance lease obligations        Finance lease obligations
 6  Operating lease obligations (2)  Operating lease obligations (2)
 7         Purchase obligations (3)         Purchase obligations (3)
 8  Other long-term liabilities (4)  Other long-term liabilities (4)
 9    Total contractual obligations    Total contractual obligations

                                 2       3        4      5   6   7   8   \
 0                              NaN     NaN      NaN    NaN NaN NaN NaN
 1                              NaN     NaN      NaN    NaN NaN NaN NaN
 2                      In millions   Total    Total  Total NaN NaN NaN
 3             Debt obligations (1)       $  13,380Â    NaN NaN NaN NaN
 4     Interest on debt obligations  9,056Â   9,056Â    NaN NaN NaN NaN
 5        Finance lease obligations       3        3      3 NaN NaN NaN
 6  Operating lease obligations (2)     468      468    468 NaN NaN NaN
 7         Purchase obligations (3)  1,654Â   1,654Â    NaN NaN NaN NaN
 8  Other long-term liabilities (4)    657Â     657Â    NaN NaN NaN NaN
 9    Total contractual obligations       $  25,218Â    NaN NaN NaN NaN

        9   ...  32    33      34      35  36  37  38                 39  \
 0     NaN  ... NaN   NaN     NaN     NaN NaN NaN NaN                NaN
 1     NaN  ... NaN   NaN     NaN     NaN NaN NaN NaN  2027 & thereafter
 2    2022  ... NaN  2026    2026  2026.0 NaN NaN NaN  2027 & thereafter
 3       $  ... NaN     $    661Â     NaN NaN NaN NaN                  $
 4    328Â  ... NaN  443Â    443Â     NaN NaN NaN NaN             6,864Â
 5      1Â  ... NaN     2       2     2.0 NaN NaN NaN                  0
 6      91  ... NaN    40      40    40.0 NaN NaN NaN                104
 7  1,178Â  ... NaN    1Â      1Â     NaN NaN NaN NaN                 5Â
 8     74Â  ... NaN   33Â     33Â     NaN NaN NaN NaN               415Â
 9       $  ... NaN     $  1,180Â     NaN NaN NaN NaN                  $

                   40                 41
 0                NaN                NaN
 1  2027 & thereafter  2027 & thereafter
 2  2027 & thereafter  2027 & thereafter
 3            10,149Â                NaN
 4             6,864Â                NaN
 5                  0                  0
 6                104                104
 7                 5Â                NaN
 8               415Â                NaN
 9            17,537Â                NaN

 [10 rows x 42 columns]]

In [35]:
soup2

[                                                   0   \
 0                                                 NaN
 1                                                   Â
 2                                         In millions
 3           Net cash provided by operating activities
 4               Net cash used in investing activities
 5       Net cash provided before financing activities
 6   Adjustment: Cash income taxes for merger trans...
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN
 14                                     Free cash flow

                                                    1   \
 0                                                 NaN
 1                                                   Â
 2                                         In millions
 3           Net cash provided by operating activities
 4               Net cash used in investing activities
 5       Net cash provided before financing activities
 6   Adjustment: Cash income taxes for merger trans...
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN
 14                                     Free cash flow

                                                    2   \
 0                                                 NaN
 1                                                   Â
 2                                         In millions
 3           Net cash provided by operating activities
 4               Net cash used in investing activities
 5       Net cash provided before financing activities
 6   Adjustment: Cash income taxes for merger trans...
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                                                NaN
 11                                                NaN
 12                                                NaN
 13                                                NaN
 14                                     Free cash flow

                              3                            4   \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                          2022                         2022
 3                             $                         570Â
 4                         (101)                        (101)
 5                          469Â                         469Â
 6                          102Â                         102Â
 7                           NaN                          NaN
 8                           NaN                          NaN
 9                           NaN                          NaN
 10                          NaN                          NaN
 11                          NaN                          NaN
 12                          NaN                          NaN
 13                          NaN                          NaN
 14                            $                         571Â

                              5                            6   \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                          2022                          NaN
 3                           NaN                          NaN
 4                           NaN                          NaN
 5                           NaN                          NaN
 6                           NaN                          NaN
 7                           NaN                          NaN
 8                           NaN                          NaN
 9                           NaN                          NaN
 10                          NaN                          NaN
 11                          NaN                          NaN
 12                          NaN                          NaN
 13                          NaN                          NaN
 14                          NaN                          NaN

                              7                            8   \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                           NaN                          NaN
 3                           NaN                          NaN
 4                           NaN                          NaN
 5                           NaN                          NaN
 6                           NaN                          NaN
 7                           NaN                          NaN
 8                           NaN                          NaN
 9                           NaN                          NaN
 10                          NaN                          NaN
 11                          NaN                          NaN
 12                          NaN                          NaN
 13                          NaN                          NaN
 14                          NaN                          NaN

                              9                            10  \
 0                           NaN                          NaN
 1   Three months ended March 31  Three months ended March 31
 2                          2021                         2021
 3                             $                         952Â
 4                         (413)                        (413)
 5                          539Â                         539Â
 6                          âÂ                         âÂ
 7                           NaN                          NaN
 8                           NaN                          NaN
 9                           NaN                          NaN
 10                          NaN                          NaN
 11                          NaN                          NaN
 12                          NaN                          NaN
 13                          NaN                          NaN
 14                            $                         539Â

                              11
 0                           NaN
 1   Three months ended March 31
 2                          2021
 3                           NaN
 4                           NaN
 5                           NaN
 6                           NaN
 7                           NaN
 8                           NaN
 9                           NaN
 10                          NaN
 11                          NaN
 12                          NaN
 13                          NaN
 14                          NaN  ]